topic:
  - document
  - sentence
length:
  - document:
     - char_limit: 100
     - word_limit: 20
     - sentence_limit: 5
  - sentence:
    - word_limit: 5
    - char_limit: 25
quality:
  - document
  - sentence
lang:
  - sentence
  - document

