replace:
  - word_level:
    - common: "the"
      special: "a"
delete:
  - word_level:
    - special: "and"
    - common: "that"
filter:
  - word_level:
    - special: "of"
  - sentence_level:
  - doc_level:
